# Generated by Django 3.2.5 on 2021-11-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('teacher', models.CharField(blank=True, max_length=30)),
                ('room', models.CharField(blank=True, max_length=20)),
                ('week', models.CharField(choices=[('1', '月曜'), ('2', '火曜'), ('3', '水曜'), ('4', '木曜'), ('5', '金曜'), ('6', '土曜')], default=1, max_length=1)),
                ('period', models.CharField(choices=[('1', '１限'), ('2', '２限'), ('3', '３限'), ('4', '４限'), ('5', '５限'), ('6', '６限'), ('7', '７限')], default=1, max_length=1)),
            ],
        ),
    ]
