# Generated by Django 3.2.18 on 2023-03-12 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('teacher', models.CharField(blank=True, max_length=30)),
                ('room', models.CharField(blank=True, max_length=20)),
                ('week', models.CharField(choices=[('1', '月曜'), ('2', '火曜'), ('3', '水曜'), ('4', '木曜'), ('5', '金曜'), ('6', '土曜')], default=1, max_length=1)),
                ('period', models.CharField(choices=[('1', '１限'), ('2', '２限'), ('3', '３限'), ('4', '４限'), ('5', '５限'), ('6', '６限'), ('7', '７限')], default=1, max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
